"""Test data factories using factory_boy"""

import factory
from factory import Faker, LazyAttribute, Sequence
from factory.alchemy import SQLAlchemyModelFactory
from storage.index_models import Node, Snapshot
from storage.manager import NodeKind
from storage.training_models import LabelRun, ModelRun, SamplePrediction, TrainingSample


class BaseFactory(SQLAlchemyModelFactory):
    """Base factory with common configuration"""

    class Meta:
        abstract = True
        sqlalchemy_session_persistence = "commit"


class SnapshotFactory(BaseFactory):
    """Factory for creating Snapshot instances"""

    class Meta:
        model = Snapshot

    snapshot_id = Sequence(lambda n: n + 1)
    created_at = "2024-01-01T00:00:00"
    root_path = "/test"
    root_abs_path = "/test"


class NodeFactory(BaseFactory):
    """Factory for creating Node instances"""

    class Meta:
        model = Node

    node_id = Sequence(lambda n: n + 1)
    snapshot_id = 1
    name = Sequence(lambda n: f"node_{n}")
    kind = NodeKind.DIR
    parent_node_id = None
    depth = 0
    rel_path = LazyAttribute(lambda obj: obj.name)
    abs_path = LazyAttribute(lambda obj: f"/test/{obj.name}")
    ext = None
    file_source = "filesystem"

    @factory.post_generation
    def setup_paths(obj, create, extracted, **kwargs):
        """Setup rel_path and abs_path based on parent if provided"""
        if not create:
            return

        if obj.parent_node_id and hasattr(obj, "_parent"):
            parent = obj._parent
            obj.rel_path = f"{parent.rel_path}/{obj.name}"
            obj.abs_path = f"{parent.abs_path}/{obj.name}"


class FileNodeFactory(NodeFactory):
    """Factory for creating File Node instances"""

    kind = NodeKind.FILE
    ext = ".txt"
    name = Sequence(lambda n: f"file_{n}.txt")


class LabelRunFactory(BaseFactory):
    """Factory for creating LabelRun instances"""

    class Meta:
        model = LabelRun

    # id is auto-generated by the database
    snapshot_id = 1
    label_source = "test"


class TrainingSampleFactory(BaseFactory):
    """Factory for creating TrainingSample instances"""

    class Meta:
        model = TrainingSample

    # sample_id is auto-generated by the database
    label_run_id = 1
    snapshot_id = 1
    node_id = Sequence(lambda n: n + 100)
    name_raw = Faker("word")
    name_norm = LazyAttribute(lambda obj: obj.name_raw.lower())
    kind = "dir"
    file_source = "filesystem"
    text = Faker("sentence")
    label = factory.Iterator(
        ["asset_type", "content_subject", "creator_or_studio", "descriptor", "other"]
    )
    split = "train"
    depth = 1


class ModelRunFactory(BaseFactory):
    """Factory for creating ModelRun instances"""

    class Meta:
        model = ModelRun

    # run_id is auto-generated by the database
    started_at = "2024-01-01T00:00:00"
    status = "running"
    run_type = "evaluation"
    base_model_id = "setfit-evaluation-v2"
    model_version = "test-model"
    model_type = "setfit"
    taxonomy = "v2"
    hyperparameters_json = "{}"
    training_data_source = None
    finished_at = None
    test_samples_count = None
    final_val_accuracy = None
    final_val_f1 = None
    notes = None


class SamplePredictionFactory(BaseFactory):
    """Factory for creating SamplePrediction instances"""

    class Meta:
        model = SamplePrediction

    # prediction_id is auto-generated by the database
    run_id = 1
    sample_id = Sequence(lambda n: n + 1)
    predicted_label = "variant"
    confidence = 0.95
    probabilities_json = '{"variant": 0.95, "subject": 0.05}'
    true_label = "variant"
    is_correct = True
    prediction_type = "test"
