"""Test data factories using factory_boy"""

import factory
from factory import Faker, LazyAttribute, SelfAttribute, Sequence
from sqlalchemy.orm import object_session
from factory.alchemy import SQLAlchemyModelFactory
from api.api import StructureType
from storage.index_models import Node, Snapshot
from storage.manager import NodeKind, RunStatus
from storage.training_models import LabelRun, ModelRun, SamplePrediction, TrainingSample
from storage.work_models import (
    Classification,
    FileMapping,
    FolderStructure,
    GroupCategory,
    GroupCategoryEntry,
    GroupEntry,
    GroupIteration,
    Meta as WorkMeta,
    Run,
    StageState,
    PartialNameCategory,
)


class BaseFactory(SQLAlchemyModelFactory):
    """Base factory with common configuration"""

    class Meta:
        abstract = True
        sqlalchemy_session_persistence = "commit"


class SnapshotFactory(BaseFactory):
    """Factory for creating Snapshot instances"""

    class Meta:
        model = Snapshot

    snapshot_id = Sequence(lambda n: n + 1)
    created_at = "2024-01-01T00:00:00"
    root_path = "/test"
    root_abs_path = "/test"


class NodeFactory(BaseFactory):
    """Factory for creating Node instances"""

    class Meta:
        model = Node

    node_id = Sequence(lambda n: n + 1)
    snapshot_id = Sequence(lambda n: n + 1)
    name = Sequence(lambda n: f"node_{n}")
    kind = NodeKind.DIR
    parent_node_id = None
    depth = 0
    rel_path = LazyAttribute(lambda obj: obj.name)
    abs_path = LazyAttribute(lambda obj: f"/test/{obj.name}")
    ext = None
    file_source = "filesystem"

    @factory.post_generation
    def setup_paths(obj, create, extracted, **kwargs):
        """Setup rel_path and abs_path based on parent if provided"""
        if not create:
            return

        if obj.parent_node_id and hasattr(obj, "_parent"):
            parent = obj._parent
            obj.rel_path = f"{parent.rel_path}/{obj.name}"  # type: ignore[attr-defined]
            obj.abs_path = f"{parent.abs_path}/{obj.name}"  # type: ignore[attr-defined]


class FileNodeFactory(NodeFactory):
    """Factory for creating File Node instances"""

    kind = NodeKind.FILE
    ext = ".txt"
    name = Sequence(lambda n: f"file_{n}.txt")


class LabelRunFactory(BaseFactory):
    """Factory for creating LabelRun instances"""

    class Meta:
        model = LabelRun

    # id is auto-generated by the database
    snapshot_id = 1
    label_source = "test"


class TrainingSampleFactory(BaseFactory):
    """Factory for creating TrainingSample instances"""

    class Meta:
        model = TrainingSample

    # sample_id is auto-generated by the database
    label_run = factory.SubFactory(LabelRunFactory)
    label_run_id = SelfAttribute("label_run.id")
    snapshot_id = SelfAttribute("label_run.snapshot_id")
    node_id = Sequence(lambda n: n + 100)
    name_raw = Faker("word")
    name_norm = LazyAttribute(lambda obj: obj.name_raw.lower())
    kind = "dir"
    file_source = "filesystem"
    text = Faker("sentence")
    label = factory.Iterator(
        ["asset_type", "content_subject", "creator_or_studio", "descriptor", "other"]
    )
    split = "train"
    depth = 1


class ModelRunFactory(BaseFactory):
    """Factory for creating ModelRun instances"""

    class Meta:
        model = ModelRun

    # run_id is auto-generated by the database
    started_at = "2024-01-01T00:00:00"
    status = "running"
    run_type = "evaluation"
    base_model_id = "setfit-evaluation-v2"
    model_version = "test-model"
    model_type = "setfit"
    taxonomy = "v2"
    hyperparameters_json = "{}"
    training_data_source = None
    finished_at = None
    test_samples_count = None
    final_val_accuracy = None
    final_val_f1 = None
    notes = None


class SamplePredictionFactory(BaseFactory):
    """Factory for creating SamplePrediction instances"""

    class Meta:
        model = SamplePrediction

    # prediction_id is auto-generated by the database
    run = factory.SubFactory(ModelRunFactory)
    run_id = SelfAttribute("run.run_id")
    sample = factory.SubFactory(TrainingSampleFactory)
    sample_id = SelfAttribute("sample.sample_id")
    predicted_label = "variant"
    confidence = 0.95
    probabilities_json = '{"variant": 0.95, "subject": 0.05}'
    true_label = "variant"
    is_correct = True
    prediction_type = "test"


class RunFactory(BaseFactory):
    """Factory for creating Run instances"""

    class Meta:
        model = Run

    snapshot_id = Sequence(lambda n: n + 1)
    started_at = "2024-01-01T00:00:00"
    finished_at = None
    status = RunStatus.RUNNING.value
    pipeline_version = None
    config_hash = None
    model_id = None
    notes = None


class StageStateFactory(BaseFactory):
    """Factory for creating StageState instances"""

    class Meta:
        model = StageState

    stage_name = Sequence(lambda n: f"stage_{n}")
    run = factory.SubFactory(RunFactory)
    run_id = SelfAttribute("run.id")
    snapshot_id = SelfAttribute("run.snapshot_id")
    completed_at = None
    input_fingerprint = None
    output_fingerprint = None


class GroupIterationFactory(BaseFactory):
    """Factory for creating GroupIteration instances"""

    class Meta:
        model = GroupIteration

    run = factory.SubFactory(RunFactory)
    run_id = SelfAttribute("run.id")
    snapshot_id = SelfAttribute("run.snapshot_id")
    timestamp = None
    description = "test iteration"
    parameters = None


class GroupEntryFactory(BaseFactory):
    """Factory for creating GroupEntry instances"""

    class Meta:
        model = GroupEntry

    iteration = factory.SubFactory(GroupIterationFactory)
    iteration_id = SelfAttribute("iteration.id")
    node_id = Sequence(lambda n: n + 1)
    cluster_id = None
    pre_processed_name = Faker("word")
    processed_name = LazyAttribute(lambda obj: obj.pre_processed_name)
    derived_names_json = None
    confidence = 1.0
    processed = False


class GroupCategoryFactory(BaseFactory):
    """Factory for creating GroupCategory instances"""

    class Meta:
        model = GroupCategory

    iteration = factory.SubFactory(GroupIterationFactory)
    iteration_id = SelfAttribute("iteration.id")
    name = Faker("word")
    count = None
    group_confidence = None
    needs_review = False
    reviewed = False


class GroupCategoryEntryFactory(BaseFactory):
    """Factory for creating GroupCategoryEntry instances"""

    class Meta:
        model = GroupCategoryEntry

    folder_id = Sequence(lambda n: n + 1)
    partial_category_id = None
    group_id = None
    iteration_id = None
    cluster_id = None
    processed_name = Faker("word")
    pre_processed_name = LazyAttribute(lambda obj: obj.processed_name)
    derived_names = None
    path = LazyAttribute(lambda obj: f"/test/{obj.folder_id}")
    confidence = 1.0
    processed = False

    @factory.post_generation
    def iteration(self, create, extracted, **kwargs):
        if extracted is not None:
            self.iteration_id = extracted.id
        elif self.iteration_id is None and create:
            iteration = GroupIterationFactory()
            self.iteration_id = iteration.id

        if create:
            session = object_session(self)
            if session:
                session.add(self)
                session.commit()


class PartialNameCategoryFactory(BaseFactory):
    """Factory for creating PartialNameCategory instances"""

    class Meta:
        model = PartialNameCategory

    name = Faker("word")
    original_name = None
    classification = None
    node_id = Sequence(lambda n: n + 1)
    hidden = False
    confidence = 1.0


class ClassificationFactory(BaseFactory):
    """Factory for creating Classification instances"""

    class Meta:
        model = Classification

    run = factory.SubFactory(RunFactory)
    run_id = SelfAttribute("run.id")
    node_id = Sequence(lambda n: n + 1)
    classification = None
    confidence = None
    method = None


class FolderStructureFactory(BaseFactory):
    """Factory for creating FolderStructure instances"""

    class Meta:
        model = FolderStructure

    run = factory.SubFactory(RunFactory)
    run_id = SelfAttribute("run.id")
    structure_type = StructureType.organized.value
    structure = {"name": "root", "children": []}
    created_at = None


class FileMappingFactory(BaseFactory):
    """Factory for creating FileMapping instances"""

    class Meta:
        model = FileMapping

    run = factory.SubFactory(RunFactory)
    run_id = SelfAttribute("run.id")
    node_id = Sequence(lambda n: n + 1)
    original_path = LazyAttribute(lambda obj: f"/test/file_{obj.node_id}.txt")
    new_path = None
    groups = None


class WorkMetaFactory(BaseFactory):
    """Factory for creating Work Meta instances"""

    class Meta:
        model = WorkMeta

    key = Sequence(lambda n: f"key_{n}")
    value = None
